function spm_ROI_about

msgbox(...
    {'spm_ROI performs fMRI statistical analyses on Regions of Interest (ROIs)',...
    'This tool was developed by members of the Speechlab at the',...
    'Cognitive and Neural Systems Department, Boston University',...
    'It needs SPM99 installed and added to the Matlab path',...
    'v.1.0 (2002)',...
    'Questions and comments: alfnie@bu.edu'},...
    'spm_ROI');
