#!/bin/csh
set bin=mris_ca_train
foreach hemi (rh lh)
    set echo=1
    $bin -n 2 $hemi sphere.reg ${hemi}-parc.annot $1 $2 $3 $4 $5 $6 $7 $8 $9 $SUBJECTS_DIR/averages/{$10}{$hemi}_SpeechLabAtlas01.gcs
end

