function output = vtkReorient(vertices,...
		faces)
% VTKREORIENT is an autogenerated mex wrapper that describes the arguments
% that are needed for the mex file operation.
% For polydata input:
% vertices type=double
% faces    type=int32 and min(faces)==1 not 0
